name: cgp
#Ios version:
#version: 1.1.4+1
#Android version:
version: 1.0.5+1000050
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0-190.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  image_cropper: ^9.0.0
  #image_cropper: ^5.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  #flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.10
  drop_down_search_field: ^1.0.4
  #carousel_slider: ^4.2.1
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  location: ^7.0.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  google_places_flutter: ^2.0.8
  flutter_stripe: ^11.1.0
  firebase_messaging: ^15.0.0
  #flutter_local_notifications: ^17.1.2
  flutter_local_notifications: ^17.2.3
  firebase_core: ^3.0.0
  url_launcher: ^6.3.0
  audioplayers: ^6.0.0
  vibration: ^2.0.0
  firebase_analytics: ^11.1.0
  flutter_rating_bar: ^4.0.1
  socket_io_client: ^2.0.3+1
  pusher_client_fixed: ^0.0.4+2
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  shared_preferences: ^2.5.2

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter: 
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf


    - family: ProximaNovaFont
      fonts:
        - asset: assets/fonts/proxima_nova_font.otf
        - asset: assets/fonts/ProximaNova-Black.ttf
        - asset: assets/fonts/ProximaNova-Bold.ttf
        - asset: assets/fonts/ProximaNova-Extrabld.ttf
        - asset: assets/fonts/ProximaNova-Light.ttf
        - asset: assets/fonts/ProximaNova-Regular.ttf
        - asset: assets/fonts/ProximaNova-Semibold.ttf
        - asset: assets/fonts/ProximaNovaT-Thin.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/sound.wav
    - assets/sound.mp3
    - assets/notification_sound.wav



flutter_native_splash:
  color: "#FFFFFF"
  # image: assets/logo/splash_screen.png
  image: assets/logo/icon.jpg
  # branding: assets/logo/launcher_icon.png
  color_dark: "#FFFFFF"
  #image_dark: assets/logo/splash_screen.png
  image_dark: assets/logo/icon.jpg
  # branding_dark: assets/logo/launcher_icon.png

  android_12:
    #image: assets/logo/splash_screen.png
    image: assets/logo/icon.jpg
    icon_background_color: "#FFFFFF"
    #image_dark: assets/logo/splash_screen.png
    image_dark: assets/logo/icon.jpg
